spring:
  application:
    name: spring_cloud_gateway_meter
  config:
    import: optional:nacos:${spring.application.name}.yml
  cloud:
    nacos:
      discovery:
        username: nacos
        password: nacos
        group: DEFAULT_GROUP
        server-addr: localhost:8848
        namespace:

    gateway:
      discovery:
        locator:
          enabled: true  #????nacos??????? ????
          lower-case-service-id: true
      routes:
        - id: query-service-route-id-0
          uri: http://localhost:8888/
          #uri: lb://redis-session
          predicates:
            - Path=/test/**
        - id: query-service-route-id-1
          uri: http://localhost:8888/
          predicates:
            - Path=/gw/**
server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: prometheus
        #include: health,info,prometheus
  metrics:
    tags:
      application: ${spring.application.name}  # ??????????????
  endpoint:
    prometheus:
      enabled: true

logging:
  level:
    root: info